#!/bin/bash

echo "🚀 HydraBot - GitHub Repository Setup"
echo "====================================="
echo ""
echo "Your local Git repository is ready!"
echo ""
echo "📋 To create a GitHub repository, follow these steps:"
echo ""
echo "OPTION 1: Using GitHub CLI (gh) - FASTEST"
echo "----------------------------------------"
echo "If you have GitHub CLI installed:"
echo ""
echo "  gh auth login"
echo "  gh repo create hydrabot --public --source=. --remote=origin --push"
echo ""
echo "Or for a private repository:"
echo ""
echo "  gh repo create hydrabot --private --source=. --remote=origin --push"
echo ""
echo ""
echo "OPTION 2: Using GitHub Web Interface"
echo "------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: hydrabot"
echo "3. Description: Smart text-based reminder assistant with SMS/Telegram support"
echo "4. Choose Public or Private"
echo "5. DO NOT initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "7. Then run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/hydrabot.git"
echo "   git push -u origin main"
echo ""
echo ""
echo "OPTION 3: Install GitHub CLI first"
echo "-----------------------------------"
echo "If you don't have GitHub CLI, install it:"
echo ""
echo "  # On Ubuntu/Debian"
echo "  sudo apt install gh"
echo ""
echo "  # Or via snap"
echo "  sudo snap install gh"
echo ""
echo "  # Then authenticate and create repo"
echo "  gh auth login"
echo "  gh repo create hydrabot --public --source=. --remote=origin --push"
echo ""
echo ""
echo "✅ Your current git status:"
git status
echo ""
echo "📊 Files committed:"
git log --oneline
echo ""
echo "Ready to push to GitHub! 🎉"
